version: "3.8"
services:
  db:
    image: "postgres:latest"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: .
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    networks:
      - backend
    env_file:
      - .env
volumes:
  db:
networks:
  backend:
    driver: bridge
