version: "3.8"
services:
  db:
    image: "postgres:latest"
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    env_file:
      - .env
  server:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "4000:4000"
    networks:
      - backend
    env_file:
      - .env
volumes:
  db:
networks:
  backend:
    driver: bridge
